### ISSUE TITLE
i register rhel7 to rhn, and want to sync rhel5/6, but get "Peer's Certificate issuer is not recognized."

### ISSUE THREAD

**Issue by gitblessk** [pyther/upstream_sync#10]
I registered rhel7, it can sync rhel7, but not rhel6, I build up another rhel6, and it can sync rhel6 too.

then I copied the pem files to rhel7, but it can't sync, keep telling me "Peer's Certificate issuer is not recognized."

How can I fix it?

Thanks.

[root@rhn scripts]# ./upstream_sync.py  --root
WARNING:root:Traceback (most recent call last):
  File "/usr/bin/reposync", line 343, in <module>
    main()
  File "/usr/bin/reposync", line 175, in main
    my.doRepoSetup()
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 681, in doRepoSetup
    return self._getRepos(thisrepo, True)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 721, in _getRepos
    self._repos.doSetup(thisrepo)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 157, in doSetup
    self.retrieveAllMD()
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 88, in retrieveAllMD
    dl = repo._async and repo._commonLoadRepoXML(repo)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1470, in _commonLoadRepoXML
    result = self._getFileRepoXML(local, text)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1248, in _getFileRepoXML
    size=102400) # setting max size as 100K
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1037, in _getFile
    raise e
yum.Errors.NoMoreMirrorsRepoError: failure: repodata/repomd.xml from rhel-6-server-rpms: [Errno 256] No more mirrors to try.
https://cdn.redhat.com/content/dist/rhel/server/6/6Server/x86_64/os/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate issuer is not recognized."

**Comment by pyther** [comment]
Have you followed these instructions? https://github.com/pyther/upstream_sync#getting-the-certificates

How did you register the RHEL7 box, how about the RHEL6 box? Providing the commands you used could be helpful in figuring out what you may have done.

**Comment by gitblessk** [comment]
I use RHEL7's cert, and it works :)
